<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FLLAP0570-MaheshNarvanes-MacBook-Air.local" failures="0" tests="10" name="PARTNERS_Flow.EasyPay" time="10.168" errors="1" timestamp="2023-08-04T10:48:00 IST" skipped="9">
  <testcase classname="PARTNERS_Flow.EasyPay" name="bsConfig" time="10.168">
    <error message="DataBase Connection was not successfull" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: DataBase Connection was not successfull
at GenericUtilities.DataBaseUtility.connectToDB(DataBaseUtility.java:53)
at GenericUtilities.BaseClass.bsConfig(BaseClass.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- bsConfig -->
  <system-out/>
  <testcase classname="PARTNERS_Flow.EasyPay" name="EasyPay_landingPage" time="0.000">
    <skipped/>
  </testcase> <!-- EasyPay_landingPage -->
  <system-out/>
  <testcase classname="PARTNERS_Flow.EasyPay" name="form1" time="0.000">
    <skipped/>
  </testcase> <!-- form1 -->
  <system-out/>
  <testcase classname="PARTNERS_Flow.EasyPay" name="form2" time="0.000">
    <skipped/>
  </testcase> <!-- form2 -->
  <system-out/>
  <testcase classname="PARTNERS_Flow.EasyPay" name="form3" time="0.000">
    <skipped/>
  </testcase> <!-- form3 -->
  <system-out/>
  <testcase classname="PARTNERS_Flow.EasyPay" name="Setu" time="0.000">
    <skipped/>
  </testcase> <!-- Setu -->
  <system-out/>
  <testcase classname="PARTNERS_Flow.EasyPay" name="BankStatement" time="0.000">
    <skipped/>
  </testcase> <!-- BankStatement -->
  <system-out/>
  <testcase classname="PARTNERS_Flow.EasyPay" name="DocumentUpload" time="0.000">
    <skipped/>
  </testcase> <!-- DocumentUpload -->
  <system-out/>
  <testcase classname="PARTNERS_Flow.EasyPay" name="form4" time="0.000">
    <skipped/>
  </testcase> <!-- form4 -->
  <system-out/>
  <testcase classname="PARTNERS_Flow.EasyPay" name="form5" time="0.000">
    <skipped/>
  </testcase> <!-- form5 -->
  <system-out/>
</testsuite> <!-- PARTNERS_Flow.EasyPay -->
